/**
 * https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#root-layout-required
 * https://nextjs.org/docs/app/building-your-application/routing#file-conventions
 */

import "@/app/globals.css";

export const metadata = {
  title: "Basic Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,700,0,0"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
