export const metadata = {
  title: "Parallel Routes",
  description: "Generated by create next app",
};

export default function Layout({
  children,
  board,
  login,
}: {
  children: React.ReactNode;
  board: React.ReactNode;
  login: React.ReactNode;
}) {
  return (
    <>
      {children}
      {board}
      {login}
    </>
  );
}
