const experienceInfos = [
  {
    period: { from: "2024. 05", to: "현재" },
    href: "https://www.wanted.co.kr/gigs",
    title: "원티드긱스",
    titleLabel: "wanted-gigs",
    subTitle: ["프리랜서"],
    skillLinks: [],
    skills: [
      "React",
      "Next.js",
      "JavaScript",
      "TypeScript",
    ],
    description: [
      "프로젝트 단위 개발",
      "- CJ대한통운 사내 관제 시스템 개발",
      "- SKDND 주거 임대 서비스 개발",
    ],
  },
  {
    period: { from: "2020. 09", to: "2023. 04" },
    href: "http://hackers.iwinv.net/",
    title: "해커스홀딩스",
    titleLabel: "hackersholdings",
    subTitle: ["연구개발 3부 · 과장 (42개월)"],
    skillLinks: [],
    skills: [
      "React",
      "React Native",
      "Node.js",
      "JavaScript",
      "TypeScript",
      "PHP",
      "MariaDB",
    ],
    description: [
      "주로 암호화폐 관련 서비스 개발에 참여, 여러 포지션에 걸쳐서 웹 및 앱을 개발",
      "- 거래소 연동 지갑 시스템",
      "- 암호화폐 시세 정보 수집 및 트레이딩뷰를 이용한 거래소 차트 구현",
      "- 실시간 암호화폐 정보를 위한 카카오톡 봇",
      "- 상품 결제를 위한 PG 앱 개발 및 구글 플레이스토어 출시",
      "- 청소 중개 서비스 관리자 웹프로그램",
    ],
  },
  {
    period: { from: "2018. 06", to: "2019. 05" },
    href: null,
    title: "한국영상솔루션 & 하나로팜",
    titleLabel: "한국영상솔루션",
    subTitle: ["선임연구원 (12개월)"],
    skillLinks: [],
    skills: ["Node.js", "JavaScript", "jQuery", "HTML", "CSS", "MariaDB"],
    description: ["농장 자율 재배(스마트팜)를 목표로 서비스를 개발"],
  },
  {
    period: { from: "2014. 04", to: "2015. 12" },
    href: "http://www.ubiot.co.kr/",
    title: "유비아이오티",
    titleLabel: "ubiot",
    subTitle: ["사원 (21개월)"],
    skillLinks: [],
    skills: ["Java", "jQuery", "HTML", "CSS", "Oracle"],
    description: [
      "KT 모바일 회원의 USIM 정보 관리 시스템 개발 및 운영",
      "협력사로 시작 후 합류함",
    ],
  },
];

export default experienceInfos;
