/**
 * 로그인 인증 여부에 따라 페이지 처리 가능
 */

// import { getUser } from "@/app/lib/auth"

export const metadata = {
  title: "Parallel Routes 2",
  description: "Generated by create next app",
};

export default function Layout({
  board,
  login,
}: {
  board: React.ReactNode;
  login: React.ReactNode;
}) {
  // const isLoggedIn = getUser();
  // const isLoggedIn = false;
  const isLoggedIn = true;

  return isLoggedIn ? board : login;
}
