/**
 * https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#root-layout-required
 * https://nextjs.org/docs/app/building-your-application/routing#file-conventions
 */

import "@/app/globals.css";
import { Cursor } from "../ui/Cursor";
import { roboto, jamsil } from "@/fonts";

export const metadata = {
  title: "Jang Hyeong-su",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${roboto.className} ${jamsil.className}`}>
      <body className="bg-slate-900 leading-relaxed antialiased text-slate-400 selection:bg-teal-300 selection:text-teal-900">
        <div className="relative">
          <Cursor />
          {children}
        </div>
      </body>
    </html>
  );
}
