/**
 * https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#root-layout-required
 * https://nextjs.org/docs/app/building-your-application/routing#file-conventions
 */

import "@/app/globals.css";
import { Roboto, Courier_Prime } from "next/font/google";

const roboto = Roboto({
  weight: "500",
  subsets: ["latin"],
  display: "swap",
});

const courier = Courier_Prime({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "My Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="bg-slate-900 leading-relaxed antialiased text-slate-400 selection:bg-teal-300 selection:text-teal-900">
        {children}
      </body>
    </html>
  );
}
